services:
  frontend:
    build:
      context: .
      target: dev
    container_name: vite_app
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - app_shop_network

networks:
  app_shop_network:
    external: true
