services:
  backend:
    extends:
      file: ./backend/docker-compose.yaml
      service: mongodb
  frontend:
    extends:
      file: ./frontend/docker-compose.yaml
      service: apache      
volumes:
  mongodb:  
networks: 
  app_shop:
    driver: bridge