services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - app_shop_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      - "traefik.enable=false"

  api:
    build:
      context: backend/api
      target: production
    container_name: shop_books_api
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - backend/api/.env
    networks:
      - app_shop_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build:
      context: frontend/
      target: production
    container_name: shop_books_nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app_shop_network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb:

networks:
  app_shop_network:
    driver: bridge
