services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
      - app_shop
volumes:
  mongodb:  
networks: 
  app_shop:
    driver: bridge
