services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-admin}
    ports:
      - "27017:27017"
    command: --quiet
    volumes:
      - mongodb:/data/db
    networks:
      - app_shop_network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../backend/api
      target: dev
    container_name: backend_api
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy
    env_file:
      - ../backend/api/.env
    volumes:
      - ../backend/api:/api
      - /api/node_modules
    networks:
      - app_shop_network
    restart: unless-stopped

  cache:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass admin1234
    volumes:
      - cache:/data
    networks:
      - app_shop_network

  frontend:
    build:
      context: ../frontend
      target: dev
    container_name: vite_app
    ports:
      - "8080:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    networks:
      - app_shop_network
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mongodb:
  cache:
    driver: local

networks:
  app_shop_network:
    driver: bridge
